language: node_js
node_js:
  - 10
services:
  - docker
script: npm run build && docker build -t $DOCKER_USERNAME/callback-proxy-service .
deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    tags: true
